service: serverless-intro

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

functions:
  getTodo:
    handler: todo/todo.get
    events:
      - http:
            path: todo
            method: get
            cors: true
